### ISSUE TITLE
dependabot issues

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/example#2]
@dni i coped your PR branch into a new github repo and it gave me all these dependabot issues. 

Just thought you'd like to know

<img width="803" alt="Screenshot 2023-04-28 at 11 47 23 AM" src="https://user-images.githubusercontent.com/73979971/235229421-ad378192-3fda-4c9d-9e42-ca731fc6254f.png">

**Comment by dni** [comment]
yep, some issue on lnbits itself, need fastapi update, there is this PR from me  https://github.com/lnbits/lnbits/pull/1609
and the openssl issue comes from pyln.
